import Link from "next/link";
import { BriefcaseBusiness, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getCareerOpportunityCatalog } from "@/server/career-hub/queries";

export default async function CareerOpportunitiesPage() {
  const opportunities = await getCareerOpportunityCatalog();
  return <div className="space-y-8"><header><p className="text-sm font-black uppercase text-brand-red">Nice Jobs</p><h1 className="mt-3 text-4xl font-black text-brand-dark">Opportunities</h1><p className="mt-3 max-w-3xl font-semibold text-brand-muted">Employment, freelance, contract, internship, project, apprenticeship, and self-employment pathways.</p></header>{opportunities.length === 0 ? <Card><CardContent className="flex min-h-40 items-center gap-4 p-6"><BriefcaseBusiness className="h-8 w-8 text-brand-red" /><p className="font-bold text-brand-muted">No authorized opportunities are currently visible. No listings were invented or seeded.</p></CardContent></Card> : <div className="grid gap-4 lg:grid-cols-2">{opportunities.map((opportunity) => <Card key={opportunity.id}><CardContent className="p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-brand-red">{opportunity.type.replaceAll("_", " ")}</p><h2 className="mt-2 text-2xl font-black text-brand-dark">{opportunity.title}</h2><p className="mt-1 font-bold text-brand-muted">{opportunity.employer.name}</p></div><span className="rounded-full bg-brand-beige px-3 py-1 text-xs font-black">{opportunity.status}</span></div><p className="mt-4 line-clamp-3 font-semibold leading-7 text-brand-muted">{opportunity.publicDescription}</p><div className="mt-4 flex flex-wrap gap-3 text-sm font-bold text-brand-muted"><span>{opportunity.workMode}</span>{opportunity.location ? <span className="flex items-center gap-1"><MapPin className="h-4 w-4" />{opportunity.location}</span> : null}<span>{opportunity._count.applications} applications</span></div><Button asChild className="mt-5" variant="secondary"><Link href={`/career/opportunities/${opportunity.code}`}>View Opportunity</Link></Button></CardContent></Card>)}</div>}</div>;
}
