export const platformRoles = [
  "Student",
  "Telecaller",
  "Counsellor",
  "Trainer",
  "Academic Advisor",
  "Director",
  "CEO",
  "COO",
  "HOD",
  "HR Manager",
  "HR Executive",
  "Interviewer",
  "Admission",
  "Business Development",
  "Relationship Manager",
  "Admin",
  "Career Hub Manager",
  "Career Participant",
  "Opportunity Owner",
  "Records Manager",
  "Compliance Manager",
  "Finance Manager",
  "Communications Manager",
  "Automation Manager",
  "People & Operations Head",
  "Admissions & Growth Head",
  "Academic Head",
  "Finance & Compliance Head",
  "Technology & Products Head",
  "Career & Partnerships Head",
  "HR & Operations Executive",
  "Hub Coordinator",
  "Admission Officer",
  "Mentor",
  "Finance Executive",
  "Marketing & Communications Executive",
  "Product Contributor",
  "AIRA Labs Member",
  "Career Operations",
  "Platform Administrator"
] as const;

export type PlatformRole = (typeof platformRoles)[number];
