import Link from "next/link";
import { BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getMySkillStudioLearning } from "@/server/skill-studio/queries";

export default async function MySkillStudioPage() {
  const enrollments = await getMySkillStudioLearning();
  return <div className="space-y-8"><header><p className="text-sm font-black uppercase text-brand-red">AIRA Skill Studio</p><h1 className="mt-3 text-4xl font-black text-brand-dark">My Skill Programs</h1><p className="mt-3 max-w-3xl font-semibold leading-7 text-brand-muted">Your active and historical Skill Studio enrollments, batches, curriculum, and trainers.</p></header>{enrollments.length === 0 ? <Card><CardContent className="flex min-h-40 items-center gap-4 p-6"><BookOpen className="h-8 w-8 text-brand-red" /><p className="font-bold text-brand-muted">No Skill Studio enrollment is linked to your account.</p></CardContent></Card> : <div className="grid gap-4 lg:grid-cols-2">{enrollments.map((enrollment) => <Card key={enrollment.id}><CardContent className="p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-brand-red">{enrollment.program.skillStudioType?.replaceAll("_", " ")}</p><h2 className="mt-2 text-2xl font-black text-brand-dark">{enrollment.program.name}</h2></div><span className="rounded-full bg-brand-beige px-3 py-1 text-xs font-black">{enrollment.status}</span></div><dl className="mt-5 grid gap-2 text-sm font-bold text-brand-muted"><div>Batch: <span className="text-brand-dark">{enrollment.batch?.name ?? "Assignment pending"}</span></div><div>Curriculum: <span className="text-brand-dark">{enrollment.journey.name}</span></div><div>Delivery: <span className="text-brand-dark">{enrollment.batch?.deliveryMode ?? enrollment.program.deliveryMode}</span></div><div>Trainer: <span className="text-brand-dark">{enrollment.batch?.trainerAssignments.map((item) => item.trainer.name).join(", ") || "Not assigned"}</span></div></dl>{enrollment.status === "ACTIVE" ? <Button asChild className="mt-5"><Link href="/my-journey">Open Learning</Link></Button> : null}</CardContent></Card>)}</div>}</div>;
}
