import Link from "next/link";
import { BookOpen, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CreateSkillStudioProgramForm } from "@/features/skill-studio/components/skill-studio-forms";
import { getSkillStudioCatalog, getSkillStudioCreateOptions } from "@/server/skill-studio/queries";

export default async function SkillStudioCatalogPage() {
  const data = await getSkillStudioCatalog();
  const raw = data.canCreate ? await getSkillStudioCreateOptions() : null;
  const options = raw ? { institutions: raw[0], divisions: raw[1], campuses: raw[2], departments: raw[3] } : null;
  return <div className="space-y-10"><header><p className="text-sm font-black uppercase text-brand-red">AIRA Skill Studio</p><h1 className="mt-3 text-4xl font-black text-brand-dark">Program Catalog</h1><p className="mt-3 max-w-3xl font-semibold leading-7 text-brand-muted">Short-form and professional skill programs using the central academic, trainer, enrollment, and organization architecture.</p></header>{options ? <Card><CardContent className="p-6 md:p-8"><div className="mb-6 flex items-center gap-3"><Plus className="h-5 w-5 text-brand-red" /><h2 className="text-xl font-black">Create Skill Studio Program</h2></div><CreateSkillStudioProgramForm options={options} /></CardContent></Card> : null}<section><h2 className="mb-5 text-2xl font-black text-brand-dark">Programs</h2>{data.programs.length === 0 ? <Card><CardContent className="flex min-h-40 items-center gap-4 p-6"><BookOpen className="h-8 w-8 text-brand-red" /><p className="font-bold text-brand-muted">No Skill Studio programs are classified yet. Existing programs were not guessed or moved.</p></CardContent></Card> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.programs.map((program) => <Card key={program.id}><CardContent className="p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-brand-red">{program.skillStudioType?.replaceAll("_", " ")}</p><h3 className="mt-2 text-xl font-black text-brand-dark">{program.name}</h3></div><span className="rounded-full bg-brand-beige px-3 py-1 text-xs font-black text-brand-dark">{program.status}</span></div><p className="mt-3 line-clamp-3 font-semibold text-brand-muted">{program.description}</p><dl className="mt-5 grid gap-2 text-sm font-bold text-brand-muted"><div>Delivery: <span className="text-brand-dark">{program.deliveryMode}</span></div><div>Learning: <span className="text-brand-dark">{program.learningModel}</span></div><div>Batches: <span className="text-brand-dark">{program._count.batches}</span></div><div>Enrollments: <span className="text-brand-dark">{program._count.enrollments}</span></div></dl><Button asChild variant="secondary" className="mt-5"><Link href={`/skill-studio/${program.slug}`}>Open Program</Link></Button></CardContent></Card>)}</div>}</section></div>;
}
