import { notFound } from "next/navigation";
import { archiveInternalChannelAction, deactivateInternalChannelMemberAction, markInternalChannelReadAction, setInternalChannelMemberRoleAction } from "@/actions/communications";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AddInternalChannelMemberForm, InternalMessageForm } from "@/features/communications/components/internal-channel-forms";
import { getInternalChannelDetail } from "@/server/communications/queries";

export default async function InternalChannelPage({ params }: { params: Promise<{ channelId: string }> }) {
  const { channelId } = await params;
  const data = await getInternalChannelDetail(channelId);
  if (!data) notFound();
  const canPost = data.channel.type === "TEAM" || data.membership.role !== "MEMBER";
  const scope = [data.channel.division?.name, data.channel.district?.name, data.channel.campus?.name, data.channel.department?.name].filter(Boolean).join(" / ");
  return <div className="space-y-8"><header className="flex flex-col gap-5 border-b border-black/10 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-black uppercase text-brand-red">{data.channel.type.replaceAll("_", " ")}</p><h1 className="mt-2 text-3xl font-black">{data.channel.name}</h1><p className="mt-2 font-semibold text-brand-muted">{data.channel.institution.name}{scope ? ` / ${scope}` : ""}</p>{data.channel.description ? <p className="mt-2 max-w-3xl text-brand-muted">{data.channel.description}</p> : null}</div><form action={markInternalChannelReadAction}><input type="hidden" name="channelId" value={channelId} /><Button variant="secondary">Mark read</Button></form></header>
    <div className="grid gap-6 xl:grid-cols-[1fr_320px]"><section><div className="space-y-3">{data.channel.messages.map((message) => <div key={message.id} className={`rounded-lg border border-black/8 p-4 ${message.authorId === data.actor.id ? "bg-brand-beige" : "bg-white"}`}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">{message.author.name}</p><time className="text-xs font-semibold text-brand-muted">{message.createdAt.toLocaleString()}</time></div><p className="mt-2 whitespace-pre-wrap leading-7 text-brand-dark">{message.body}</p></div>)}{data.channel.messages.length === 0 ? <Card><CardContent className="p-6 font-semibold text-brand-muted">No messages yet.</CardContent></Card> : null}</div>{canPost ? <Card className="mt-5"><CardContent className="p-6"><InternalMessageForm channelId={channelId} /></CardContent></Card> : <Card className="mt-5"><CardContent className="p-6 font-semibold text-brand-muted">Only owners and moderators can post in this announcement channel.</CardContent></Card>}</section>
      <aside className="space-y-5"><Card><CardContent className="p-5"><h2 className="font-black">Members</h2><div className="mt-4 space-y-4">{data.channel.members.map((member) => <div key={member.id} className="border-b border-black/8 pb-3 last:border-0"><p className="font-bold">{member.user.name}</p><p className="text-xs font-bold text-brand-muted">{member.role}</p>{data.canManage && member.role !== "OWNER" ? <div className="mt-2 flex flex-wrap gap-2"><form action={setInternalChannelMemberRoleAction} className="flex gap-2"><input type="hidden" name="channelId" value={channelId} /><input type="hidden" name="userId" value={member.userId} /><select name="role" defaultValue={member.role} className="h-10 rounded-lg border border-black/10 bg-white px-2 text-sm font-bold"><option value="MEMBER">Member</option><option value="MODERATOR">Moderator</option></select><Button variant="secondary">Update</Button></form><form action={deactivateInternalChannelMemberAction}><input type="hidden" name="channelId" value={channelId} /><input type="hidden" name="userId" value={member.userId} /><Button variant="secondary">Remove</Button></form></div> : null}</div>)}</div></CardContent></Card>{data.canManage ? <Card><CardContent className="p-5"><h2 className="mb-4 font-black">Channel management</h2><AddInternalChannelMemberForm channelId={channelId} employees={data.employees} /><form action={archiveInternalChannelAction} className="mt-5 border-t border-black/10 pt-5"><input type="hidden" name="channelId" value={channelId} /><Button variant="secondary">Archive channel</Button></form></CardContent></Card> : null}<Card><CardContent className="p-5"><h2 className="font-black">SIA boundary</h2><p className="mt-2 text-sm font-semibold leading-6 text-brand-muted">SIA may help a human draft text in an approved assistant workspace. It cannot read this channel merely by existing, join members, or post autonomously.</p></CardContent></Card></aside></div>
  </div>;
}
