import Link from "next/link";
import { CheckCircle2, CreditCard, FileText, KeyRound, MessageCircle, ShieldCheck, Timer, Users } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DirectorMetricCard } from "@/features/director/components/director-metric-card";
import { DirectorPageHeader } from "@/features/director/components/director-page-header";
import { getAdminCommandCenter } from "@/server/admin/queries";

export const dynamic = "force-dynamic";

export default async function AdminDashboardPage() {
  const data = await getAdminCommandCenter();

  const departments = [
    { title: "Applications", href: "/admissions/applications", detail: `${data.stats.totalApplications} total records`, icon: FileText },
    { title: "Review", href: "/admissions/review", detail: `${data.admissions.stats.pendingReview} waiting`, icon: CheckCircle2 },
    { title: "Admissions", href: "/admissions/approved", detail: `${data.stats.approvedWithoutLogin} need login access`, icon: ShieldCheck },
    { title: "Fee", href: "/admissions/payments", detail: `${data.admissions.stats.pendingPayments} pending invoices`, icon: CreditCard }
  ];

  return (
    <div className="space-y-10">
      <DirectorPageHeader eyebrow="Admin" title="AIRA Skill City Command Center" description="Control admissions, review, fees and student login activation from one simple operating view." />

      <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
        <DirectorMetricCard label="Applications" value={data.stats.totalApplications} icon={FileText} />
        <DirectorMetricCard label="Review Queue" value={data.admissions.stats.pendingReview} icon={CheckCircle2} />
        <DirectorMetricCard label="Approved, Login Pending" value={data.stats.approvedWithoutLogin} icon={KeyRound} />
        <DirectorMetricCard label="Active Student Logins" value={data.stats.activeStudentLogins} icon={Users} />
        <DirectorMetricCard label="Temporary PINs" value={data.stats.temporaryPins} icon={Timer} />
        <DirectorMetricCard label="Expired PINs" value={data.stats.expiredPins} icon={Timer} />
        <DirectorMetricCard label="Open Programs" value={data.stats.openPrograms} icon={ShieldCheck} />
        <DirectorMetricCard label="Waiting List Programs" value={data.stats.waitlistPrograms} icon={MessageCircle} />
      </section>

      <section className="grid gap-5 lg:grid-cols-4">
        {departments.map((item) => (
          <Link key={item.href} href={item.href} className="rounded-lg border border-black/8 bg-brand-card p-6 transition hover:-translate-y-1 hover:shadow-soft">
            <item.icon className="h-7 w-7 text-brand-red" />
            <h2 className="mt-5 text-2xl font-black text-brand-dark">{item.title}</h2>
            <p className="mt-2 font-semibold text-brand-muted">{item.detail}</p>
          </Link>
        ))}
      </section>

      <section className="grid gap-5 lg:grid-cols-[1fr_420px]">
        <Card>
          <CardContent className="p-6">
            <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
              <div>
                <h2 className="text-2xl font-black text-brand-dark">Recent WhatsApp Login Messages</h2>
                <p className="mt-2 font-semibold text-brand-muted">PIN messages generated by the Admission Cell appear here.</p>
              </div>
              <Button asChild variant="secondary">
                <Link href="/admin/access">View access</Link>
              </Button>
            </div>
            <div className="mt-6 space-y-3">
              {data.whatsappMessages.length === 0 ? (
                <p className="font-semibold text-brand-muted">No WhatsApp login messages yet.</p>
              ) : (
                data.whatsappMessages.map((message) => (
                  <div key={message.id} className="rounded-lg bg-white p-4">
                    <p className="font-black text-brand-dark">{message.application?.lead.name ?? message.user?.name ?? message.to}</p>
                    <p className="mt-1 text-sm font-bold text-brand-muted">{message.template} - {message.status} - {message.to}</p>
                  </div>
                ))
              )}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <h2 className="text-2xl font-black text-brand-dark">Launch Priorities</h2>
            <div className="mt-6 space-y-3">
              {[
                "Review submitted applications daily.",
                "Generate WhatsApp PIN only after approval.",
                "Collect fee or mark free program enrollment clearly.",
                "Activate dashboard after student resets PIN."
              ].map((item) => (
                <div key={item} className="rounded-lg bg-white p-4 font-bold text-brand-muted">{item}</div>
              ))}
            </div>
          </CardContent>
        </Card>
      </section>
    </div>
  );
}
