import { notFound } from "next/navigation";
import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { InvoiceStatusForm } from "@/features/core-operations/components/core-operation-forms";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { requirePermission } from "@/server/auth/authorization";
import { getFinanceInvoiceDetail } from "@/server/core-operations/queries";

export default async function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) { const actor = await requirePermission(PERMISSIONS.FINANCE_READ); const { id } = await params; const invoice = await getFinanceInvoiceDetail(id); if (!invoice) notFound(); const paid = invoice.transactions.filter((payment) => payment.status === "SUCCESS").reduce((sum, payment) => sum + payment.amount, 0); const currency = invoice.currency ?? "Currency not recorded"; return <div className="space-y-8"><PageHeader title={invoice.invoiceNo} subtitle={`${invoice.status} · ${currency} ${invoice.total}`} />{hasPermission(actor, PERMISSIONS.FINANCE_INVOICE_MANAGE) ? <Card><CardContent className="p-6"><InvoiceStatusForm id={invoice.id} status={invoice.status} /></CardContent></Card> : null}<div className="grid gap-5 lg:grid-cols-2"><Card><CardContent className="p-6"><h2 className="text-xl font-black">Invoice</h2><dl className="mt-4 space-y-2 font-semibold text-brand-muted"><div>Organization: {invoice.institution?.name ?? "Inherited legacy scope"}</div><div>Program: {invoice.program?.name ?? "Not linked"}</div><div>Customer: {invoice.student?.name ?? invoice.lead?.name ?? "Not linked"}</div><div>Subtotal: {currency} {invoice.subtotal}</div><div>Discount: {currency} {invoice.discount}</div><div>Tax: {currency} {invoice.gst}</div><div>Verified paid: {currency} {paid}</div></dl></CardContent></Card><Card><CardContent className="p-6"><h2 className="text-xl font-black">Payments</h2><div className="mt-4 space-y-3">{invoice.transactions.map((payment) => <div key={payment.id} className="border-b border-black/10 pb-3"><p className="font-black">{payment.provider} · {payment.status}</p><p className="text-sm font-semibold text-brand-muted">{currency} {payment.amount} · {payment.providerRef ?? "No provider reference"}</p></div>)}</div></CardContent></Card></div></div>; }
