import { notFound } from "next/navigation";
import { Card, CardContent } from "@/components/ui/card";
import { CareerApplicationForm, CareerReferralForm } from "@/features/career-hub/components/career-hub-forms";
import { getCareerOpportunityDetail } from "@/server/career-hub/queries";

function formatDate(value: Date | null) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(value) : "No deadline"; }

export default async function CareerOpportunityDetailPage({ params }: { params: Promise<{ code: string }> }) {
  const { code } = await params;
  const data = await getCareerOpportunityDetail(code);
  if (!data.opportunity) notFound();
  const opportunity = data.opportunity;
  return <div className="space-y-8"><header><p className="text-sm font-black uppercase text-brand-red">{opportunity.type.replaceAll("_", " ")}</p><h1 className="mt-3 text-4xl font-black text-brand-dark">{opportunity.title}</h1><p className="mt-2 text-xl font-bold text-brand-muted">{opportunity.employer.name}</p></header><div className="grid gap-6 lg:grid-cols-[1fr_0.7fr]"><Card><CardContent className="p-6 md:p-8"><h2 className="text-2xl font-black text-brand-dark">Opportunity</h2><p className="mt-4 whitespace-pre-line font-semibold leading-7 text-brand-muted">{opportunity.publicDescription}</p><dl className="mt-6 grid gap-3 text-sm font-bold text-brand-muted"><div>Work mode: <span className="text-brand-dark">{opportunity.workMode}</span></div><div>Location: <span className="text-brand-dark">{opportunity.location ?? "Flexible / not specified"}</span></div><div>Required skills: <span className="text-brand-dark">{opportunity.requiredSkills.join(", ") || "Not specified"}</span></div><div>Compensation: <span className="text-brand-dark">{opportunity.compensationSummary ?? "Discussed by employer"}</span></div><div>Deadline: <span className="text-brand-dark">{formatDate(opportunity.applicationDeadline)}</span></div><div>Employer verification: <span className="text-brand-dark">{opportunity.employer.status}</span></div></dl></CardContent></Card><div className="space-y-5">{data.existingApplication ? <Card><CardContent className="p-6"><p className="text-sm font-black uppercase text-brand-red">Application Status</p><p className="mt-2 text-2xl font-black text-brand-dark">{data.existingApplication.status.replaceAll("_", " ")}</p></CardContent></Card> : data.canApply && opportunity.status === "OPEN" ? <Card><CardContent className="p-6"><h2 className="mb-5 text-xl font-black text-brand-dark">Apply</h2><CareerApplicationForm opportunityId={opportunity.id} /></CardContent></Card> : null}{data.canRefer && opportunity.status === "OPEN" ? <Card><CardContent className="p-6"><h2 className="mb-3 text-xl font-black text-brand-dark">Referral</h2><p className="mb-4 text-sm font-semibold leading-6 text-brand-muted">Creates attribution only. No coins, commission, or payout is awarded.</p><CareerReferralForm opportunityId={opportunity.id} /></CardContent></Card> : null}</div></div></div>;
}
