import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { EventAutomationForm, ProcessEventsForm } from "@/features/communications/components/communication-forms";
import { getAutomationOperations } from "@/server/communications/queries";

export default async function CommunicationsAutomationsPage() {
  const { rules, executions, institutions, canManage } = await getAutomationOperations();
  return <div><PageHeader title="Automation Operations" subtitle="Allowlisted event-to-notification rules with durable execution records and bounded retries." />{canManage ? <div className="space-y-5"><Card><CardContent className="p-6"><EventAutomationForm institutions={institutions} /></CardContent></Card><Card><CardContent className="p-6"><ProcessEventsForm /></CardContent></Card></div> : null}<section className="mt-10"><h2 className="text-2xl font-black">Definitions</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{rules.map((rule) => <Card key={rule.id}><CardContent className="p-6"><p className="text-xs font-black uppercase text-brand-red">{rule.code ?? "Legacy definition"}</p><h3 className="mt-2 text-xl font-black">{rule.name}</h3><p className="mt-2 text-sm text-brand-muted">{rule.eventType ?? rule.triggerType} → {rule.actionType} · {rule.institution?.name ?? "Global"}</p><p className="mt-2 text-sm font-bold">{rule.active ? "Active" : "Inactive"} · {rule.executions.length} recent runs</p></CardContent></Card>)}</div></section><section className="mt-10"><h2 className="text-2xl font-black">Recent executions</h2><div className="mt-4 space-y-3">{executions.map((item) => <Card key={item.id}><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-black">{item.rule.name}</p><p className="text-sm text-brand-muted">{item.domainEvent?.type ?? "Legacy / manual"}</p></div><div className="text-right"><p className="font-black text-brand-red">{item.status}</p><p className="text-sm text-brand-muted">Attempt {item.attempts}/{item.maxAttempts}</p></div></CardContent></Card>)}</div></section></div>;
}
