import { notFound } from "next/navigation";
import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { getCoreDocumentDetail } from "@/server/core-operations/queries";

export default async function DocumentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const document = await getCoreDocumentDetail(id);
  if (!document) notFound();
  return <div className="space-y-8"><PageHeader title={document.displayName} subtitle={`${document.code} · ${document.category} · ${document.status}`} /><div className="grid gap-5 lg:grid-cols-2"><Card><CardContent className="p-6"><h2 className="text-xl font-black">Access and ownership</h2><dl className="mt-4 space-y-2 font-semibold text-brand-muted"><div>Policy: {document.accessPolicy}</div><div>Organization: {document.institution.name}</div><div>Owner: {document.owner?.name ?? "Organization record"}</div><div>Created by: {document.createdBy.name}</div><div>Retention: {document.retentionUntil?.toLocaleDateString() ?? "Not defined"}</div></dl></CardContent></Card><Card><CardContent className="p-6"><h2 className="text-xl font-black">Authorized contexts</h2><div className="mt-4 space-y-2">{document.contextLinks.map((link) => <p key={link.id} className="font-semibold text-brand-muted">{link.contextType}: {link.contextId}</p>)}{document.contextLinks.length === 0 ? <p className="font-semibold text-brand-muted">No context links.</p> : null}</div></CardContent></Card></div><Card><CardContent className="p-6"><h2 className="text-xl font-black">Version history</h2><div className="mt-4 divide-y divide-black/10">{document.versions.map((version) => <div key={version.id} className="py-4"><p className="font-black">Version {version.version} · {version.originalFilename}</p><p className="mt-1 text-sm font-semibold text-brand-muted">{version.mimeType} · {version.sizeBytes ?? "Unknown"} bytes · {version.storageProvider} · uploaded by {version.uploadedBy.name}</p></div>)}</div><p className="mt-4 text-sm font-semibold text-brand-muted">Private storage keys are intentionally not displayed. A signed download service is deferred until a provider is selected.</p></CardContent></Card></div>;
}
