"use client";

import { useActionState } from "react";
import { createComplianceRecordAction, createCoreDocumentAction, createFinanceInvoiceAction, recordFinancePaymentAction, updateComplianceStatusAction, updateFinanceInvoiceStatusAction, verifyFinancePaymentAction } from "@/actions/core-operations";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DirectorFormMessage } from "@/features/director/components/director-form-message";

const initialState = { ok: false, message: "" };
type Option = { id: string; name: string };
type Options = { institutions: Option[]; divisions: Option[]; districts: Option[]; campuses: Option[]; departments: Option[]; employees: Array<{ id: string; user: { name: string } }>; programs: Option[] };

function Select({ name, label, children, required }: { name: string; label: string; children: React.ReactNode; required?: boolean }) { return <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span><select name={name} required={required} className="h-12 w-full rounded-lg border border-black/10 bg-white px-4 font-semibold">{children}</select></label>; }
function OrgFields({ options }: { options: Options }) { return <div className="grid gap-4 md:grid-cols-3"><Select name="institutionId" label="Organization" required><option value="">Select</option>{options.institutions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select name="divisionId" label="Division"><option value="">None</option>{options.divisions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select name="districtId" label="District"><option value="">None</option>{options.districts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select name="campusId" label="Centre"><option value="">None</option>{options.campuses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select name="departmentId" label="Department"><option value="">None</option>{options.departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></div>; }

export function CoreDocumentForm({ options }: { options: Options }) {
  const [state, action, pending] = useActionState(createCoreDocumentAction, initialState);
  return <form action={action} className="space-y-4"><DirectorFormMessage {...state} /><OrgFields options={options} /><div className="grid gap-4 md:grid-cols-3"><Input name="code" label="Document Code" required /><Input name="displayName" label="Display Name" required /><Select name="category" label="Category" required>{["IDENTITY","CONTRACT","AGREEMENT","CERTIFICATE","INVOICE","RECEIPT","APPLICATION_RECORD","PORTFOLIO","COMPLIANCE","POLICY","OTHER"].map((v) => <option key={v}>{v}</option>)}</Select></div><div className="grid gap-4 md:grid-cols-3"><Select name="accessPolicy" label="Access Policy" required>{["PRIVATE","OWNER","ORGANIZATION","AUTHORIZED_CONTEXT"].map((v) => <option key={v}>{v}</option>)}</Select><Input name="retentionUntil" label="Retention Until" type="date" /><Input name="originalFilename" label="Original Filename" required /></div><div className="grid gap-4 md:grid-cols-3"><Input name="mimeType" label="MIME Type" required /><Input name="sizeBytes" label="Size (bytes)" type="number" /><Input name="storageProvider" label="Storage Provider" required /></div><Input name="storageKey" label="Private Storage Reference" required /><p className="text-sm font-semibold text-brand-muted">Storage references are retained server-side and are not rendered as download links.</p><Button disabled={pending}>{pending ? "Registering..." : "Register Document"}</Button></form>;
}

export function ComplianceRecordForm({ options }: { options: Options }) {
  const [state, action, pending] = useActionState(createComplianceRecordAction, initialState);
  return <form action={action} className="space-y-4"><DirectorFormMessage {...state} /><OrgFields options={options} /><div className="grid gap-4 md:grid-cols-3"><Input name="code" label="Compliance Code" required /><Input name="title" label="Title" required /><Select name="subjectType" label="Subject Type" required>{["ORGANIZATION","EMPLOYEE","STUDENT","EMPLOYER","PROGRAM","DOCUMENT","OTHER"].map((v) => <option key={v}>{v}</option>)}</Select></div><Input name="subjectId" label="Subject Reference" /><div className="grid gap-4 md:grid-cols-2"><Select name="responsibleEmployeeId" label="Responsible Employee"><option value="">None</option>{options.employees.map((item) => <option key={item.id} value={item.id}>{item.user.name}</option>)}</Select><Select name="reviewerEmployeeId" label="Reviewer"><option value="">None</option>{options.employees.map((item) => <option key={item.id} value={item.id}>{item.user.name}</option>)}</Select></div><div className="grid gap-4 md:grid-cols-3"><Input name="effectiveAt" label="Effective Date" type="date" /><Input name="expiresAt" label="Expiry Date" type="date" /><Input name="reviewAt" label="Review Date" type="date" /></div><Button disabled={pending}>{pending ? "Creating..." : "Create Compliance Record"}</Button></form>;
}

export function ComplianceStatusForm({ id, status }: { id: string; status: string }) { const [state, action, pending] = useActionState(updateComplianceStatusAction, initialState); return <form action={action} className="flex flex-wrap items-end gap-3"><input type="hidden" name="complianceRecordId" value={id} /><Select name="status" label="Status">{["PENDING","ACTIVE","EXPIRED","REJECTED","WAIVED","ARCHIVED"].map((v) => <option key={v} selected={v === status}>{v}</option>)}</Select><Button size="md" disabled={pending}>Update</Button><DirectorFormMessage {...state} /></form>; }

export function FinanceInvoiceForm({ programs }: { programs: Option[] }) { const [state, action, pending] = useActionState(createFinanceInvoiceAction, initialState); return <form action={action} className="space-y-4"><DirectorFormMessage {...state} /><div className="grid gap-4 md:grid-cols-3"><Select name="programId" label="Program" required><option value="">Select</option>{programs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Input name="invoiceNo" label="Invoice Number" required /><Input name="currency" label="Currency" defaultValue="INR" maxLength={3} required /></div><div className="grid gap-4 md:grid-cols-4"><Input name="subtotal" label="Subtotal (minor units)" type="number" min={1} required /><Input name="discount" label="Discount" type="number" min={0} defaultValue={0} /><Input name="tax" label="Tax" type="number" min={0} defaultValue={0} /><Input name="dueAt" label="Due Date" type="date" /></div><Input name="reference" label="Reference" /><Button disabled={pending}>{pending ? "Creating..." : "Create Draft Invoice"}</Button></form>; }

export function InvoiceStatusForm({ id, status }: { id: string; status: string }) { const [state, action, pending] = useActionState(updateFinanceInvoiceStatusAction, initialState); return <form action={action} className="flex flex-wrap items-end gap-3"><input type="hidden" name="invoiceId" value={id} /><Select name="status" label="Invoice Status">{["DRAFT","ISSUED","OVERDUE","VOID","CANCELLED"].map((v) => <option key={v} selected={v === status}>{v}</option>)}</Select><Button disabled={pending}>Update</Button><DirectorFormMessage {...state} /></form>; }

export function PaymentRecordForm({ invoices }: { invoices: Array<{ id: string; invoiceNo: string }> }) { const [state, action, pending] = useActionState(recordFinancePaymentAction, initialState); return <form action={action} className="space-y-4"><DirectorFormMessage {...state} /><div className="grid gap-4 md:grid-cols-4"><Select name="invoiceId" label="Invoice" required>{invoices.map((item) => <option key={item.id} value={item.id}>{item.invoiceNo}</option>)}</Select><Select name="provider" label="Provider" required>{["MANUAL","RAZORPAY","STRIPE","SCHOLARSHIP"].map((v) => <option key={v}>{v}</option>)}</Select><Input name="amount" label="Amount (minor units)" type="number" min={1} required /><Input name="providerRef" label="Provider Reference" required /></div><Input name="paidAt" label="Payment Date" type="date" /><Button disabled={pending}>{pending ? "Recording..." : "Record for Verification"}</Button></form>; }

export function PaymentVerificationForm({ id }: { id: string }) { const [state, action, pending] = useActionState(verifyFinancePaymentAction, initialState); return <form action={action} className="flex flex-wrap items-end gap-3"><input type="hidden" name="paymentId" value={id} /><Select name="decision" label="Decision"><option value="VERIFIED">Verified</option><option value="REJECTED">Rejected</option></Select><Button disabled={pending}>Save Decision</Button><DirectorFormMessage {...state} /></form>; }
