export const PERMISSIONS = {
  ADMIN_ACCESS: "admin.access",
  USER_MANAGE: "user.manage",
  ORGANIZATION_MANAGE: "organization.manage",
  EMPLOYEE_READ: "employee.read",
  EMPLOYEE_CREATE: "employee.create",
  EMPLOYEE_UPDATE: "employee.update",
  EMPLOYEE_MANAGE: "employee.manage",
  DIRECTOR_ACCESS: "director.access",
  EXECUTIVE_ACCESS: "executive.access",
  ADMISSIONS_ACCESS: "admissions.access",
  ADMISSIONS_MANAGE: "admissions.manage",
  BDM_ACCESS: "bdm.access",
  TELECALLER_ACCESS: "telecaller.access",
  COUNSELLOR_ACCESS: "counsellor.access",
  TRAINER_ACCESS: "trainer.access",
  ADVISOR_READ: "advisor.read",
  ADVISOR_ASSIGN: "advisor.assign",
  ADVISOR_MANAGE: "advisor.manage",
  LABS_READ: "labs.read",
  LABS_CREATE: "labs.create",
  LABS_UPDATE: "labs.update",
  LABS_MANAGE: "labs.manage",
  LABS_ASSIGN: "labs.assign",
  SKILL_STUDIO_READ: "skill-studio.read",
  SKILL_STUDIO_CREATE: "skill-studio.create",
  SKILL_STUDIO_UPDATE: "skill-studio.update",
  SKILL_STUDIO_MANAGE: "skill-studio.manage",
  SKILL_STUDIO_ENROLL: "skill-studio.enroll",
  SKILL_STUDIO_ASSIGN: "skill-studio.assign",
  CAREER_READ: "career.read",
  CAREER_PROFILE_MANAGE: "career.profile.manage",
  CAREER_APPLY: "career.apply",
  CAREER_OPPORTUNITY_MANAGE: "career.opportunity.manage",
  CAREER_APPLICATION_MANAGE: "career.application.manage",
  CAREER_REFERRAL_MANAGE: "career.referral.manage",
  DOCUMENTS_READ: "documents.read",
  DOCUMENTS_MANAGE: "documents.manage",
  COMPLIANCE_READ: "compliance.read",
  COMPLIANCE_MANAGE: "compliance.manage",
  FINANCE_READ: "finance.read",
  FINANCE_INVOICE_MANAGE: "finance.invoice.manage",
  FINANCE_PAYMENT_MANAGE: "finance.payment.manage",
  COMMUNICATIONS_READ: "communications.read",
  COMMUNICATIONS_MANAGE: "communications.manage",
  COMMUNICATIONS_SEND: "communications.send",
  INTERNAL_COMMUNICATIONS_READ: "internal-communications.read",
  INTERNAL_COMMUNICATIONS_SEND: "internal-communications.send",
  INTERNAL_COMMUNICATIONS_MANAGE: "internal-communications.manage",
  COMMUNICATION_TEMPLATES_MANAGE: "communication-templates.manage",
  AUTOMATIONS_READ: "automations.read",
  AUTOMATIONS_MANAGE: "automations.manage",
  RECRUITMENT_ACCESS: "recruitment.access",
  RECRUITMENT_DIRECTOR: "recruitment.director",
  RELATIONSHIP_MANAGER_ACCESS: "relationship-manager.access",
  STUDENT_ACCESS: "student.access",
  COMMUNITY_ACCESS: "community.access",
  COMMUNITY_MANAGE: "community.manage",
  COMMUNITY_EVENT_MANAGE: "community-event.manage",
  SUCCESS_ACCESS: "success.access",
  SUCCESS_REVIEW: "success.review",
  CERTIFICATE_ISSUE: "certificate.issue",
  AI_STUDENT: "ai.student",
  AI_TRAINER: "ai.trainer",
  AI_ADMISSION: "ai.admission",
  AI_BDM: "ai.bdm",
  AI_DIRECTOR: "ai.director",
  AI_USE: "ai.use",
  AI_MANAGE: "ai.manage",
  AI_AUDIT: "ai.audit",
  AI_APPROVE: "ai.approve"
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ACCESS_SCOPES = ["GLOBAL", "ORGANIZATION", "DIVISION", "DISTRICT", "BRANCH", "DEPARTMENT", "OWN"] as const;
export type AccessScope = (typeof ACCESS_SCOPES)[number];

export const ROLE_KEYS = {
  STUDENT: "STUDENT",
  TELECALLER: "TELECALLER",
  COUNSELLOR: "COUNSELLOR",
  TRAINER: "TRAINER",
  ACADEMIC_ADVISOR: "ACADEMIC_ADVISOR",
  DIRECTOR: "DIRECTOR",
  CEO: "CEO",
  COO: "COO",
  HOD: "HOD",
  HR_MANAGER: "HR_MANAGER",
  HR_EXECUTIVE: "HR_EXECUTIVE",
  INTERVIEWER: "INTERVIEWER",
  ADMISSION: "ADMISSION",
  BUSINESS_DEVELOPMENT: "BUSINESS_DEVELOPMENT",
  RELATIONSHIP_MANAGER: "RELATIONSHIP_MANAGER",
  ADMIN: "ADMIN",
  CAREER_HUB_MANAGER: "CAREER_HUB_MANAGER",
  CAREER_PARTICIPANT: "CAREER_PARTICIPANT",
  OPPORTUNITY_OWNER: "OPPORTUNITY_OWNER",
  RECORDS_MANAGER: "RECORDS_MANAGER",
  COMPLIANCE_MANAGER: "COMPLIANCE_MANAGER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  COMMUNICATIONS_MANAGER: "COMMUNICATIONS_MANAGER",
  AUTOMATION_MANAGER: "AUTOMATION_MANAGER",
  PEOPLE_OPERATIONS_HEAD: "PEOPLE_OPERATIONS_HEAD",
  ADMISSIONS_GROWTH_HEAD: "ADMISSIONS_GROWTH_HEAD",
  ACADEMIC_HEAD: "ACADEMIC_HEAD",
  FINANCE_COMPLIANCE_HEAD: "FINANCE_COMPLIANCE_HEAD",
  TECHNOLOGY_PRODUCTS_HEAD: "TECHNOLOGY_PRODUCTS_HEAD",
  CAREER_PARTNERSHIPS_HEAD: "CAREER_PARTNERSHIPS_HEAD",
  HR_OPERATIONS: "HR_OPERATIONS",
  HUB_COORDINATOR: "HUB_COORDINATOR",
  ADMISSION_OFFICER: "ADMISSION_OFFICER",
  MENTOR: "MENTOR",
  FINANCE_EXECUTIVE: "FINANCE_EXECUTIVE",
  MARKETING_COMMUNICATIONS: "MARKETING_COMMUNICATIONS",
  PRODUCT_CONTRIBUTOR: "PRODUCT_CONTRIBUTOR",
  CAREER_OPERATIONS: "CAREER_OPERATIONS",
  PLATFORM_ADMIN: "PLATFORM_ADMIN"
} as const;

export const ROLE_NAME_TO_KEY: Record<string, string> = {
  Student: ROLE_KEYS.STUDENT,
  Telecaller: ROLE_KEYS.TELECALLER,
  Counsellor: ROLE_KEYS.COUNSELLOR,
  Trainer: ROLE_KEYS.TRAINER,
  "Academic Advisor": ROLE_KEYS.ACADEMIC_ADVISOR,
  Director: ROLE_KEYS.DIRECTOR,
  CEO: ROLE_KEYS.CEO,
  COO: ROLE_KEYS.COO,
  HOD: ROLE_KEYS.HOD,
  "HR Manager": ROLE_KEYS.HR_MANAGER,
  "HR Executive": ROLE_KEYS.HR_EXECUTIVE,
  Interviewer: ROLE_KEYS.INTERVIEWER,
  Admission: ROLE_KEYS.ADMISSION,
  "Business Development": ROLE_KEYS.BUSINESS_DEVELOPMENT,
  "Relationship Manager": ROLE_KEYS.RELATIONSHIP_MANAGER,
  Admin: ROLE_KEYS.ADMIN,
  "Career Hub Manager": ROLE_KEYS.CAREER_HUB_MANAGER,
  "Career Participant": ROLE_KEYS.CAREER_PARTICIPANT,
  "Opportunity Owner": ROLE_KEYS.OPPORTUNITY_OWNER,
  "Records Manager": ROLE_KEYS.RECORDS_MANAGER,
  "Compliance Manager": ROLE_KEYS.COMPLIANCE_MANAGER,
  "Finance Manager": ROLE_KEYS.FINANCE_MANAGER,
  "Communications Manager": ROLE_KEYS.COMMUNICATIONS_MANAGER,
  "Automation Manager": ROLE_KEYS.AUTOMATION_MANAGER,
  "People & Operations Head": ROLE_KEYS.PEOPLE_OPERATIONS_HEAD,
  "Admissions & Growth Head": ROLE_KEYS.ADMISSIONS_GROWTH_HEAD,
  "Academic Head": ROLE_KEYS.ACADEMIC_HEAD,
  "Finance & Compliance Head": ROLE_KEYS.FINANCE_COMPLIANCE_HEAD,
  "Technology & Products Head": ROLE_KEYS.TECHNOLOGY_PRODUCTS_HEAD,
  "Career & Partnerships Head": ROLE_KEYS.CAREER_PARTNERSHIPS_HEAD,
  "HR & Operations Executive": ROLE_KEYS.HR_OPERATIONS,
  "Hub Coordinator": ROLE_KEYS.HUB_COORDINATOR,
  "Admission Officer": ROLE_KEYS.ADMISSION_OFFICER,
  Mentor: ROLE_KEYS.MENTOR,
  "Finance Executive": ROLE_KEYS.FINANCE_EXECUTIVE,
  "Marketing & Communications Executive": ROLE_KEYS.MARKETING_COMMUNICATIONS,
  "Product Contributor": ROLE_KEYS.PRODUCT_CONTRIBUTOR,
  "Career Operations": ROLE_KEYS.CAREER_OPERATIONS,
  "Platform Administrator": ROLE_KEYS.PLATFORM_ADMIN
};

type LegacyGrant = { permission: PermissionKey; scope: AccessScope };

const allPermissions = Object.values(PERMISSIONS).map((permission) => ({ permission, scope: "GLOBAL" as const }));
const globalBusinessPermissions = Object.values(PERMISSIONS)
  .filter((permission) => permission !== PERMISSIONS.ADMIN_ACCESS)
  .map((permission) => ({ permission, scope: "GLOBAL" as const }));
const globalDirectorPermissions = globalBusinessPermissions.filter((grant) => grant.permission !== PERMISSIONS.USER_MANAGE);
const scoped = (permissions: PermissionKey[], scope: AccessScope): LegacyGrant[] => permissions.map((permission) => ({ permission, scope }));

export const LEGACY_ROLE_GRANTS: Record<string, LegacyGrant[]> = {
  [ROLE_KEYS.ADMIN]: allPermissions,
  [ROLE_KEYS.PLATFORM_ADMIN]: scoped([PERMISSIONS.ADMIN_ACCESS, PERMISSIONS.USER_MANAGE, PERMISSIONS.AI_AUDIT], "GLOBAL"),
  [ROLE_KEYS.DIRECTOR]: globalDirectorPermissions,
  [ROLE_KEYS.CEO]: globalBusinessPermissions,
  [ROLE_KEYS.COO]: [PERMISSIONS.EXECUTIVE_ACCESS, PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.RECRUITMENT_DIRECTOR, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.AI_DIRECTOR, PERMISSIONS.LABS_READ, PERMISSIONS.LABS_CREATE, PERMISSIONS.LABS_UPDATE, PERMISSIONS.LABS_MANAGE, PERMISSIONS.LABS_ASSIGN, PERMISSIONS.SKILL_STUDIO_READ, PERMISSIONS.SKILL_STUDIO_CREATE, PERMISSIONS.SKILL_STUDIO_UPDATE, PERMISSIONS.SKILL_STUDIO_MANAGE, PERMISSIONS.SKILL_STUDIO_ENROLL, PERMISSIONS.SKILL_STUDIO_ASSIGN, PERMISSIONS.CAREER_READ, PERMISSIONS.CAREER_PROFILE_MANAGE, PERMISSIONS.CAREER_APPLY, PERMISSIONS.CAREER_OPPORTUNITY_MANAGE, PERMISSIONS.CAREER_APPLICATION_MANAGE, PERMISSIONS.CAREER_REFERRAL_MANAGE, PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.DOCUMENTS_MANAGE, PERMISSIONS.COMPLIANCE_READ, PERMISSIONS.COMPLIANCE_MANAGE, PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_INVOICE_MANAGE, PERMISSIONS.FINANCE_PAYMENT_MANAGE, PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_MANAGE, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.COMMUNICATION_TEMPLATES_MANAGE, PERMISSIONS.AUTOMATIONS_READ, PERMISSIONS.AUTOMATIONS_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE].map((permission) => ({ permission, scope: "GLOBAL" })),
  [ROLE_KEYS.HOD]: [PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.RECRUITMENT_DIRECTOR, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.LABS_READ, PERMISSIONS.LABS_CREATE, PERMISSIONS.LABS_UPDATE, PERMISSIONS.LABS_ASSIGN, PERMISSIONS.SKILL_STUDIO_READ, PERMISSIONS.SKILL_STUDIO_CREATE, PERMISSIONS.SKILL_STUDIO_UPDATE, PERMISSIONS.SKILL_STUDIO_ENROLL, PERMISSIONS.SKILL_STUDIO_ASSIGN, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.HR_MANAGER]: [PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.EMPLOYEE_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.HR_EXECUTIVE]: [PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.INTERVIEWER]: scoped([PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND], "OWN"),
  [ROLE_KEYS.ADMISSION]: [PERMISSIONS.ADMISSIONS_ACCESS, PERMISSIONS.ADMISSIONS_MANAGE, PERMISSIONS.TELECALLER_ACCESS, PERMISSIONS.COUNSELLOR_ACCESS, PERMISSIONS.AI_ADMISSION, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.BUSINESS_DEVELOPMENT]: [PERMISSIONS.BDM_ACCESS, PERMISSIONS.RELATIONSHIP_MANAGER_ACCESS, PERMISSIONS.AI_BDM, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND].map((permission) => ({ permission, scope: "OWN" })),
  [ROLE_KEYS.RELATIONSHIP_MANAGER]: [PERMISSIONS.BDM_ACCESS, PERMISSIONS.RELATIONSHIP_MANAGER_ACCESS, PERMISSIONS.AI_BDM, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND].map((permission) => ({ permission, scope: "OWN" })),
  [ROLE_KEYS.TELECALLER]: scoped([PERMISSIONS.TELECALLER_ACCESS, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND], "OWN"),
  [ROLE_KEYS.COUNSELLOR]: scoped([PERMISSIONS.COUNSELLOR_ACCESS, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND], "OWN"),
  [ROLE_KEYS.TRAINER]: [PERMISSIONS.TRAINER_ACCESS, PERMISSIONS.COMMUNITY_ACCESS, PERMISSIONS.COMMUNITY_EVENT_MANAGE, PERMISSIONS.SUCCESS_ACCESS, PERMISSIONS.SUCCESS_REVIEW, PERMISSIONS.AI_TRAINER, PERMISSIONS.SKILL_STUDIO_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND].map((permission) => ({ permission, scope: "OWN" })),
  [ROLE_KEYS.ACADEMIC_ADVISOR]: [PERMISSIONS.ADVISOR_READ, PERMISSIONS.SUCCESS_ACCESS, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND].map((permission) => ({ permission, scope: "OWN" })),
  [ROLE_KEYS.STUDENT]: [PERMISSIONS.STUDENT_ACCESS, PERMISSIONS.COMMUNITY_ACCESS, PERMISSIONS.SUCCESS_ACCESS, PERMISSIONS.AI_STUDENT, PERMISSIONS.SKILL_STUDIO_READ, PERMISSIONS.CAREER_READ, PERMISSIONS.CAREER_PROFILE_MANAGE, PERMISSIONS.CAREER_APPLY, PERMISSIONS.CAREER_REFERRAL_MANAGE].map((permission) => ({ permission, scope: "OWN" })),
  [ROLE_KEYS.CAREER_PARTICIPANT]: [PERMISSIONS.CAREER_READ, PERMISSIONS.CAREER_PROFILE_MANAGE, PERMISSIONS.CAREER_APPLY, PERMISSIONS.CAREER_REFERRAL_MANAGE].map((permission) => ({ permission, scope: "OWN" })),
  [ROLE_KEYS.CAREER_HUB_MANAGER]: [PERMISSIONS.CAREER_READ, PERMISSIONS.CAREER_PROFILE_MANAGE, PERMISSIONS.CAREER_APPLY, PERMISSIONS.CAREER_OPPORTUNITY_MANAGE, PERMISSIONS.CAREER_APPLICATION_MANAGE, PERMISSIONS.CAREER_REFERRAL_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.OPPORTUNITY_OWNER]: [PERMISSIONS.CAREER_READ, PERMISSIONS.CAREER_OPPORTUNITY_MANAGE, PERMISSIONS.CAREER_APPLICATION_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND].map((permission) => ({ permission, scope: "OWN" })),
  [ROLE_KEYS.RECORDS_MANAGER]: [PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.DOCUMENTS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.COMPLIANCE_MANAGER]: [PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.COMPLIANCE_READ, PERMISSIONS.COMPLIANCE_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.FINANCE_MANAGER]: [PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_INVOICE_MANAGE, PERMISSIONS.FINANCE_PAYMENT_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.COMMUNICATIONS_MANAGER]: [PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_MANAGE, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.COMMUNICATION_TEMPLATES_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.AUTOMATION_MANAGER]: [PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.AUTOMATIONS_READ, PERMISSIONS.AUTOMATIONS_MANAGE].map((permission) => ({ permission, scope: "ORGANIZATION" })),
  [ROLE_KEYS.PEOPLE_OPERATIONS_HEAD]: scoped([PERMISSIONS.ORGANIZATION_MANAGE, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.EMPLOYEE_MANAGE, PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_USE, PERMISSIONS.AI_APPROVE], "ORGANIZATION"),
  [ROLE_KEYS.ADMISSIONS_GROWTH_HEAD]: scoped([PERMISSIONS.ADMISSIONS_ACCESS, PERMISSIONS.ADMISSIONS_MANAGE, PERMISSIONS.BDM_ACCESS, PERMISSIONS.TELECALLER_ACCESS, PERMISSIONS.COUNSELLOR_ACCESS, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_ADMISSION, PERMISSIONS.AI_USE, PERMISSIONS.AI_APPROVE], "ORGANIZATION"),
  [ROLE_KEYS.ACADEMIC_HEAD]: scoped([PERMISSIONS.DIRECTOR_ACCESS, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.ADVISOR_READ, PERMISSIONS.ADVISOR_ASSIGN, PERMISSIONS.ADVISOR_MANAGE, PERMISSIONS.TRAINER_ACCESS, PERMISSIONS.SKILL_STUDIO_READ, PERMISSIONS.SKILL_STUDIO_CREATE, PERMISSIONS.SKILL_STUDIO_UPDATE, PERMISSIONS.SKILL_STUDIO_MANAGE, PERMISSIONS.SKILL_STUDIO_ENROLL, PERMISSIONS.SKILL_STUDIO_ASSIGN, PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_DIRECTOR, PERMISSIONS.AI_USE, PERMISSIONS.AI_APPROVE], "ORGANIZATION"),
  [ROLE_KEYS.FINANCE_COMPLIANCE_HEAD]: scoped([PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_INVOICE_MANAGE, PERMISSIONS.FINANCE_PAYMENT_MANAGE, PERMISSIONS.COMPLIANCE_READ, PERMISSIONS.COMPLIANCE_MANAGE, PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.DOCUMENTS_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_USE, PERMISSIONS.AI_APPROVE], "ORGANIZATION"),
  [ROLE_KEYS.TECHNOLOGY_PRODUCTS_HEAD]: scoped([PERMISSIONS.LABS_READ, PERMISSIONS.LABS_CREATE, PERMISSIONS.LABS_UPDATE, PERMISSIONS.LABS_MANAGE, PERMISSIONS.LABS_ASSIGN, PERMISSIONS.AUTOMATIONS_READ, PERMISSIONS.AUTOMATIONS_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_USE, PERMISSIONS.AI_MANAGE, PERMISSIONS.AI_AUDIT, PERMISSIONS.AI_APPROVE], "ORGANIZATION"),
  [ROLE_KEYS.CAREER_PARTNERSHIPS_HEAD]: scoped([PERMISSIONS.CAREER_READ, PERMISSIONS.CAREER_PROFILE_MANAGE, PERMISSIONS.CAREER_APPLY, PERMISSIONS.CAREER_OPPORTUNITY_MANAGE, PERMISSIONS.CAREER_APPLICATION_MANAGE, PERMISSIONS.CAREER_REFERRAL_MANAGE, PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_USE, PERMISSIONS.AI_APPROVE], "ORGANIZATION"),
  [ROLE_KEYS.HR_OPERATIONS]: scoped([PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.RECRUITMENT_ACCESS, PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.AI_USE], "ORGANIZATION"),
  [ROLE_KEYS.HUB_COORDINATOR]: scoped([PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.ADMISSIONS_ACCESS, PERMISSIONS.ADVISOR_READ, PERMISSIONS.TRAINER_ACCESS, PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_USE], "BRANCH"),
  [ROLE_KEYS.ADMISSION_OFFICER]: scoped([PERMISSIONS.ADMISSIONS_ACCESS, PERMISSIONS.ADMISSIONS_MANAGE, PERMISSIONS.COUNSELLOR_ACCESS, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.AI_ADMISSION, PERMISSIONS.AI_USE], "ORGANIZATION"),
  [ROLE_KEYS.MENTOR]: scoped([PERMISSIONS.TRAINER_ACCESS, PERMISSIONS.ADVISOR_READ, PERMISSIONS.COMMUNITY_ACCESS, PERMISSIONS.SUCCESS_ACCESS, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.AI_TRAINER, PERMISSIONS.AI_USE], "OWN"),
  [ROLE_KEYS.FINANCE_EXECUTIVE]: scoped([PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_INVOICE_MANAGE, PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.AI_USE], "ORGANIZATION"),
  [ROLE_KEYS.MARKETING_COMMUNICATIONS]: scoped([PERMISSIONS.COMMUNICATIONS_READ, PERMISSIONS.COMMUNICATIONS_SEND, PERMISSIONS.CAREER_READ, PERMISSIONS.BDM_ACCESS, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.INTERNAL_COMMUNICATIONS_MANAGE, PERMISSIONS.AI_USE], "ORGANIZATION"),
  [ROLE_KEYS.PRODUCT_CONTRIBUTOR]: scoped([PERMISSIONS.LABS_READ, PERMISSIONS.LABS_UPDATE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.AI_USE], "OWN"),
  [ROLE_KEYS.CAREER_OPERATIONS]: scoped([PERMISSIONS.CAREER_READ, PERMISSIONS.CAREER_APPLICATION_MANAGE, PERMISSIONS.CAREER_REFERRAL_MANAGE, PERMISSIONS.INTERNAL_COMMUNICATIONS_READ, PERMISSIONS.INTERNAL_COMMUNICATIONS_SEND, PERMISSIONS.AI_USE], "ORGANIZATION")
};

export type AuthorizationUser = {
  id: string;
  roles: Array<{
    role: {
      name: string;
      key?: string | null;
      permissions?: Array<{
        scope: AccessScope;
        permission: { key: string; active: boolean };
      }>;
    };
  }>;
  accessScopes?: Array<{
    scope: AccessScope;
    institutionId?: string | null;
    divisionId?: string | null;
    districtId?: string | null;
    campusId?: string | null;
    departmentId?: string | null;
    expiresAt?: Date | null;
  }>;
  employeeProfile?: {
    id?: string;
    status?: string;
    institutionId?: string | null;
    divisionId?: string | null;
    districtId?: string | null;
    campusId?: string | null;
    departmentId?: string | null;
    organizationAssignments?: Array<{
      institutionId: string;
      divisionId?: string | null;
      districtId?: string | null;
      campusId?: string | null;
      departmentId?: string | null;
      startsAt: Date;
      endsAt?: Date | null;
    }>;
  } | null;
};

export type ResourceScope = {
  ownerId?: string | null;
  institutionId?: string | null;
  divisionId?: string | null;
  districtId?: string | null;
  campusId?: string | null;
  departmentId?: string | null;
};

export type EffectiveScopeAssignment = ResourceScope & { scope: Exclude<AccessScope, "GLOBAL" | "OWN"> };

export type AuthorizedScopes = {
  global: boolean;
  own: boolean;
  assignments: EffectiveScopeAssignment[];
};

export function permissionGrants(user: AuthorizationUser, permission: PermissionKey) {
  return (user.roles ?? []).flatMap(({ role }) => {
    const explicit = role.permissions?.filter((item) => item.permission.active && item.permission.key === permission) ?? [];
    if ((role.permissions?.length ?? 0) > 0) return explicit.map((item) => item.scope);
    const key = role.key ?? ROLE_NAME_TO_KEY[role.name];
    const legacy = (key ? LEGACY_ROLE_GRANTS[key] ?? [] : []).filter((item) => item.permission === permission).map((item) => item.scope);
    if (legacy.length === 0 && key && permission === PERMISSIONS.COMMUNITY_ACCESS) return ["OWN" as const];
    return legacy;
  });
}

export function hasPermission(user: AuthorizationUser, permission: PermissionKey) {
  return permissionGrants(user, permission).length > 0;
}

function scopeMatches(scope: AccessScope, assignment: ResourceScope, resource: ResourceScope, userId: string) {
  if (scope === "GLOBAL") return true;
  if (scope === "OWN") return resource.ownerId === userId;
  if (scope === "ORGANIZATION") return Boolean(assignment.institutionId && assignment.institutionId === resource.institutionId);
  if (scope === "DIVISION") return Boolean(assignment.divisionId && assignment.divisionId === resource.divisionId);
  if (scope === "DISTRICT") return Boolean(assignment.districtId && assignment.districtId === resource.districtId);
  if (scope === "BRANCH") return Boolean(assignment.campusId && assignment.campusId === resource.campusId);
  if (scope === "DEPARTMENT") return Boolean(assignment.departmentId && assignment.departmentId === resource.departmentId);
  return false;
}

export function resolveAuthorizedScopes(user: AuthorizationUser, permission: PermissionKey, now = new Date()): AuthorizedScopes {
  const grants = permissionGrants(user, permission);
  const own = grants.includes("OWN");
  const hasScopedGrant = grants.some((grant) => grant !== "OWN");
  if (!hasScopedGrant) return { global: false, own, assignments: [] };

  const explicitScopes = (user.accessScopes ?? [])
    .filter((item) => item.scope !== "GLOBAL" && item.scope !== "OWN" && (!item.expiresAt || item.expiresAt > now))
    .map((item) => ({ ...item, scope: item.scope as EffectiveScopeAssignment["scope"] }));
  if (explicitScopes.length > 0) return { global: false, own, assignments: explicitScopes };
  if (grants.includes("GLOBAL")) return { global: true, own, assignments: [] };

  const profile = user.employeeProfile;
  const assignments: EffectiveScopeAssignment[] = [];
  if (profile) {
    const profiles = [
      profile,
      ...(profile.organizationAssignments ?? []).filter((assignment) => assignment.startsAt <= now && (!assignment.endsAt || assignment.endsAt > now))
    ];
    for (const assignment of profiles) {
      if (grants.includes("ORGANIZATION") && assignment.institutionId) assignments.push({ scope: "ORGANIZATION", ...assignment });
      if (grants.includes("DIVISION") && assignment.divisionId) assignments.push({ scope: "DIVISION", ...assignment });
      if (grants.includes("DISTRICT") && assignment.districtId) assignments.push({ scope: "DISTRICT", ...assignment });
      if (grants.includes("BRANCH") && assignment.campusId) assignments.push({ scope: "BRANCH", ...assignment });
      if (grants.includes("DEPARTMENT") && assignment.departmentId) assignments.push({ scope: "DEPARTMENT", ...assignment });
    }
  }
  return { global: false, own, assignments };
}

export function canAccessResource(user: AuthorizationUser, permission: PermissionKey, resource: ResourceScope, now = new Date()) {
  const resolved = resolveAuthorizedScopes(user, permission, now);
  if (resolved.global) return true;
  if (resolved.own && resource.ownerId === user.id) return true;
  return resolved.assignments.some((assignment) => scopeMatches(assignment.scope, assignment, resource, user.id));
}
